### ISSUE TITLE
PhantomJS server suddenly dies out

### ISSUE THREAD

**Issue by nullifiedaccount3** [jcalderonzumba/gastonjs#24]
PhantomJS server suddenly and frequently dies out and have to manually restart to get it to work again.

**Comment by jcalderonzumba** [comment]
You should probably provide a bit more information because this open issued provide no information at all for us so we can at least try to check why you are getting errors.

- What version of phantomJS are you using?
- Is the dying random or always dying at some particular place?
- Can you share also the trace error that you get when the server dies?

**Comment by nullifiedaccount3** [comment]
Will reopen as I have more info.
